"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, CircleHelp, MapPinned, Save } from "lucide-react";
type Behavior="aplicar"|"desativar"|"herdar";
type Rule={uf:string;regras_json:Record<string,Behavior>};
const fields=["cbenef","cbenef_alq","fecp","fecp_st","re29560"] as const;
type Field=(typeof fields)[number];
const labels:Record<Field,string>={cbenef:"cBenef (SNC)",cbenef_alq:"Alíquota cBenef (SNC)",fecp:"FECP",fecp_st:"FECP-ST",re29560:"RE 29.560"};
export default function FiscalRulesPage(){
 const [items,setItems]=useState<Rule[]>([]),[original,setOriginal]=useState<Record<string,string>>({}),[selectedField,setSelectedField]=useState<Field>("cbenef"),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 async function load(){const r=await fetch("/api/mix/v1/regras-fiscais-uf",{cache:"no-store"}),j=await r.json();if(!r.ok)return setMessage(j.detail||"Não foi possível carregar as regras.");const loaded:Rule[]=j.items||[];setItems(loaded);setOriginal(Object.fromEntries(loaded.map(item=>[item.uf.trim(),JSON.stringify(item.regras_json)])))}
 useEffect(()=>{void load()},[]);
 const allowed=useMemo(()=>items.filter(item=>item.regras_json[selectedField]==="aplicar").map(item=>item.uf.trim()),[items,selectedField]);
 const changed=items.filter(item=>original[item.uf.trim()]!==JSON.stringify(item.regras_json));
 function toggleUf(uf:string){setItems(current=>current.map(item=>item.uf.trim()!==uf?item:{...item,regras_json:{...item.regras_json,[selectedField]:item.regras_json[selectedField]==="aplicar"?"desativar":"aplicar"}}))}
 async function saveAll(){if(!changed.length)return setMessage("Nenhuma alteração para salvar.");setSaving(true);for(const item of changed){const uf=item.uf.trim(),r=await fetch("/api/mix/v1/regras-fiscais-uf",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({uf,regras:item.regras_json})}),j=await r.json();if(!r.ok){setSaving(false);return setMessage(j.detail||`Falha ao salvar as regras de ${uf}.`)}}setSaving(false);setMessage(`${changed.length} UF(s) atualizada(s). As mudanças valerão nas próximas execuções automáticas.`);await load()}
 return <main className="editor-page fiscal-rules-page"><header className="editor-header"><div><a href="/painel/templates" className="back"><ArrowLeft size={17}/> Voltar aos templates</a><span className="eyebrow dark">CONFIGURAÇÃO CENTRAL</span><h1>Regras fiscais por UF</h1><p>Escolha uma regra e clique nos estados para incluir ou remover.</p></div><button className="primary-button fiscal-save-button" disabled={saving||!changed.length} onClick={saveAll}><Save size={17}/>{saving?"Salvando...":changed.length?`Salvar alterações (${changed.length})`:"Sem alterações"}</button></header>
 {message&&<div className="rule-feedback"><Check size={17}/>{message}</div>}
 <section className="uf-rule-explanation"><CircleHelp size={22}/><div><strong>Como esta configuração funciona</strong><p>Escolha cBenef, Alíquota cBenef, FECP, FECP-ST ou RE 29.560 e clique nas UFs. Estado verde será marcado automaticamente; estado cinza será desmarcado. A regra só é usada nos templates com o modo <b>Aplicar automaticamente</b>, depois que a API identificar a UF do CNPJ. cBenef e Alíquota cBenef controlam somente o cenário SNC; a RE 29.560 pertence ao CE. Uma exceção cadastrada no template tem prioridade sobre esta lista.</p><small>As mudanças só entram em vigor depois de clicar em “Salvar alterações” e afetam apenas as próximas execuções.</small></div></section>
 <section className="uf-rule-editor"><div className="uf-rule-tabs" role="tablist" aria-label="Regra fiscal">{fields.map(field=><button key={field} type="button" role="tab" aria-selected={selectedField===field} className={selectedField===field?"selected":""} onClick={()=>setSelectedField(field)}>{labels[field]}<small>{items.filter(item=>item.regras_json[field]==="aplicar").length} UFs</small></button>)}</div>
 <div className="uf-rule-content"><div className="uf-rule-heading"><div><MapPinned size={22}/><span><strong>{labels[selectedField]}</strong><small>Verde = incluído · cinza = removido</small></span></div><code>{selectedField}_uf_allowed: [{allowed.map(uf=>`"${uf}"`).join(", ")}]</code></div><div className="uf-chip-grid">{items.map(item=>{const uf=item.uf.trim(),active=item.regras_json[selectedField]==="aplicar";return <button key={uf} type="button" aria-pressed={active} className={active?"active":""} onClick={()=>toggleUf(uf)}><span>{uf}</span>{active&&<Check size={16}/>}</button>})}</div></div></section>
 <p className="uf-rule-help">O template da retaguarda continua definindo os outros campos. Estas cinco listas somente ligam ou desligam as flags conforme a UF encontrada pela API para cada CNPJ.</p></main>
}
