"use client";
import { useEffect,useState } from "react";
import { ArrowLeft,Check,ChevronDown,ChevronUp,Copy,Pencil,Plus,Save,Sparkles,Trash2 } from "lucide-react";

type Meta={id:number;nome:string}; type Fields={view_nome:string;view_sql:string;tmp_nome:string;tmp_delete:string;flag1:boolean;flag2:boolean;flag3:boolean;tmp_insert:string;tmp_values:string;tmp_selectwhere:string};
type Data={tabelas:Record<string,Fields>;comparar_divergencia:Record<string,unknown>;excecoes_produtos:Record<string,unknown>};
const taxes=[['pis_cofins','PIS / COFINS'],['icms_saida','ICMS Saída'],['icms_entrada','ICMS Entrada'],['ibs_cbs','IBS / CBS']];
const blank=():Fields=>({view_nome:'',view_sql:'',tmp_nome:'',tmp_delete:'',flag1:false,flag2:false,flag3:false,tmp_insert:'',tmp_values:'',tmp_selectwhere:''});
const divergence:Record<string,Record<string,string[]>>={
  pis_cofins:{'PIS / COFINS':['ncm','ncmex','cod_natureza_receita','credito_presumido','pis_cst_e','pis_cst_s','pis_alq_e','pis_alq_s','cofins_cst_e','cofins_cst_s','cofins_alq_e','cofins_alq_s']},
  ibs_cbs:{'IBS / CBS':['classe_tributaria','cbs_alq','ibs_uf_alq','ibs_mun_alq','is_classe_tributaria','is_alq_especifica','ibs_cbs_cst','cbs_alq_rbc','ibs_uf_alq_rbc','ibs_mun_alq_rbc','is_alq']},
  ibs_cbs_rural:{'IBS / CBS Rural':['classe_tributaria','cbs_alq','ibs_uf_alq','ibs_mun_alq','is_classe_tributaria','is_alq_especifica','ibs_cbs_cst','cbs_alq_rbc','ibs_uf_alq_rbc','ibs_mun_alq_rbc','is_alq']},
  ibs_cbs_gov:{'IBS / CBS Governo':['classe_tributaria','cbs_alq','ibs_uf_alq','ibs_mun_alq','is_classe_tributaria','is_alq_especifica','ibs_cbs_cst','cbs_alq_rbc','ibs_uf_alq_rbc','ibs_mun_alq_rbc','is_alq']},
  icms_entrada:{EI:['ei.cst','ei.alq','ei.alqst','ei.rbc','ei.rbcst'],ED:['ed.cst','ed.alq','ed.alqst','ed.rbc','ed.rbcst'],ES:['es.cst','es.alq','es.alqst','es.rbc','es.rbcst'],NF:['nf.nfi_cst','nf.nfd_cst','nf.nfs_csosn','nf.alq'],'Outros ICMS':['outros_icms.mva','outros_icms.tipo_mva','outros_icms.mva_data_ini','outros_icms.mva_data_fim','outros_icms.cred_outorgado','outros_icms.gera_debito','outros_icms.sub_rbc_alq']},
  icms_saida:{SAC:['sac.cst','sac.alq','sac.alqst','sac.rbc','sac.rbcst','sac.cbenef_alq','sac.cest'],SAS:['sas.cst','sas.alq','sas.alqst','sas.rbc','sas.rbcst','sas.cbenef_alq','sas.re29560'],SVC:['svc.cst','svc.alq','svc.alqst','svc.rbc','svc.rbcst','svc.cbenef_alq','svc.fecp'],SNC:['snc.cst','snc.alq','snc.alqst','snc.rbc','snc.rbcst','snc.cbenef_alq','snc.fecp_st'],'Simples Nacional':['simples_nacional.sss_csosn','simples_nacional.svc_csosn','simples_nacional.snc_csosn']}
};
const divergenceMasters=[
  {key:'pis',title:'PIS / COFINS',sections:['pis_cofins']},
  {key:'ibs',title:'IBS / CBS',sections:['ibs_cbs','ibs_cbs_rural','ibs_cbs_gov']},
  {key:'entrada',title:'ICMS de Entrada',sections:['icms_entrada']},
  {key:'saida',title:'ICMS de Saída',sections:['icms_saida']},
];
function getDeep(obj:Record<string,unknown>,path:string){return path.split('.').reduce((o,k)=>(o as Record<string,unknown>)?.[k],obj as unknown)===true}
function setDeep(obj:Record<string,unknown>,path:string,value:boolean){const keys=path.split('.');let cur=obj;keys.forEach((k,i)=>{if(i===keys.length-1)cur[k]=value;else cur=cur[k] as Record<string,unknown>||(cur[k]={}) as Record<string,unknown>});}

export default function TemplatesPage(){
 const [items,setItems]=useState<Meta[]>([]),[selected,setSelected]=useState<number>(),[data,setData]=useState<Data>(),[message,setMessage]=useState(''),[expandAll,setExpandAll]=useState(false),[divergenceOpen,setDivergenceOpen]=useState(false),[openMasters,setOpenMasters]=useState<string[]>(divergenceMasters.map(master=>master.key)),[viewTax,setViewTax]=useState('pis_cofins'),[tmpTax,setTmpTax]=useState('pis_cofins');
 async function list(select?:number){const r=await fetch('/api/mix/v1/templates');const j=await r.json();setItems(j.items||[]);if(select)setSelected(select);else if(!selected&&j.items?.[0])setSelected(j.items[0].id)}
 useEffect(()=>{void list()},[]);useEffect(()=>{if(!selected)return;fetch(`/api/mix/v1/templates/${selected}`).then(r=>r.json()).then(j=>{const tables=j.dados?.tabelas||{};for(const [k] of taxes)tables[k]={...blank(),...(tables[k]||{})};setData({tabelas:tables,comparar_divergencia:j.dados?.comparar_divergencia||{},excecoes_produtos:j.dados?.excecoes_produtos||{}})})},[selected]);
 function field(tax:string,key:keyof Fields,value:string|boolean){setData(d=>d?{...d,tabelas:{...d.tabelas,[tax]:{...d.tabelas[tax],[key]:value}}}:d)}
 function append(tax:string,key:keyof Fields,text:string){field(tax,key,String(data?.tabelas[tax][key]||'')+(data?.tabelas[tax][key]?' ':'')+text)}
 async function create(copy:boolean){const nome=prompt('Nome do novo template:')?.trim();if(!nome)return;const r=await fetch('/api/mix/v1/templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nome,copiar_de:copy?selected:null})});const j=await r.json();if(!r.ok)return setMessage(j.detail);setMessage(copy?'Template copiado.':'Template criado do zero.');await list(j.id)}
 async function save(){if(!selected||!data)return;const r=await fetch(`/api/mix/v1/templates/${selected}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({dados:data})});setMessage(r.ok?'Template salvo com sucesso.':(await r.json()).detail)}
 async function remove(){const current=items.find(i=>i.id===selected);if(!current)return;const typed=prompt(`Para excluir o template "${current.nome}", digite exatamente o nome abaixo:\n\n${current.nome}`);if(typed!==current.nome)return typed!==null&&setMessage('O nome digitado não confere. Template não excluído.');const r=await fetch(`/api/mix/v1/templates/${selected}`,{method:'DELETE'});const j=await r.json();if(!r.ok)return setMessage(j.detail);setSelected(undefined);setData(undefined);await list();setMessage(`Template "${current.nome}" excluído.`)}
 return <main className="editor-page"><header className="editor-header"><div><a href="/painel" className="back"><ArrowLeft size={17}/> Voltar ao painel</a><span className="eyebrow dark">CONFIGURAÇÕES</span><h1>Templates fiscais</h1><p>Crie e mantenha as regras utilizadas pelo worker.</p></div><div className="editor-actions"><button onClick={()=>create(false)}><Plus size={17}/> Novo</button><button onClick={()=>create(true)} disabled={!selected}><Copy size={17}/> Copiar atual</button><button onClick={()=>setExpandAll(!expandAll)}>{expandAll?<ChevronUp size={17}/>:<ChevronDown size={17}/>} {expandAll?'Recolher tudo':'Expandir tudo'}</button><button className="danger-outline" onClick={remove} disabled={!selected}><Trash2 size={17}/></button><button className="primary-button compact" onClick={save} disabled={!data}><Save size={17}/> Salvar</button></div></header>
 {message&&<div className="notice"><span>{message}</span><button onClick={()=>setMessage('')}>×</button></div>}
 <section className="template-picker"><label>Template ativo<select value={selected||''} onChange={e=>setSelected(Number(e.target.value))}><option value="" disabled>Selecione</option>{items.map(i=><option key={i.id} value={i.id}>{i.nome}</option>)}</select></label><div className="rule-hint"><Sparkles size={18}/><span>Variáveis disponíveis: <code>{'{cnpj}'}</code> <code>{'{estado}'}</code> <code>{'{regime_tributario}'}</code> <code>{'{nome_empresa}'}</code></span></div></section>
 {!data?<div className="empty-editor">Selecione ou crie um template.</div>:<>
 <div className="auto-rule-note"><Sparkles size={20}/><div><strong>Proteções automáticas por cliente</strong><p>As regras <code>codigo_produto IN</code>, <code>codigo_produto NOT IN</code> e a trava <code>1=2</code> são identificadas no momento do processamento e preservadas pelo worker. Não precisam ser cadastradas no template.</p></div></div>
 <section className="tables-workspace"><div className="table-master view-master"><h2>VIEW</h2><div className="table-row-list">{taxes.map(([key,label])=><button type="button" className={viewTax===key?'active':''} key={key} onClick={()=>setViewTax(key)}><Pencil size={15}/><strong>{label}</strong><span>{data.tabelas[key].view_nome||'Não informado'}</span></button>)}</div><div className="form-stack">{(expandAll?taxes:taxes.filter(([key])=>key===viewTax)).map(([key,label])=><div className="mix-edit-form" key={key}><h3>{label} — VIEW</h3><Field label="Nome da tabela VIEW" value={data.tabelas[key].view_nome} change={v=>field(key,'view_nome',v)}/><Sql label="SELECT de consulta da VIEW" value={data.tabelas[key].view_sql} change={v=>field(key,'view_sql',v)} insert={t=>append(key,'view_sql',t)}/></div>)}</div></div><div className="table-master tmp-master"><h2>TMP</h2><div className="table-row-list">{taxes.map(([key,label])=><button type="button" className={tmpTax===key?'active':''} key={key} onClick={()=>setTmpTax(key)}><Pencil size={15}/><strong>{label}</strong><span>{data.tabelas[key].tmp_nome||'Não informado'}</span></button>)}</div><div className="form-stack">{(expandAll?taxes:taxes.filter(([key])=>key===tmpTax)).map(([key,label])=>{const f=data.tabelas[key];return <div className="mix-edit-form" key={key}><h3>{label} — TMP</h3><Field label="Nome da tabela TMP" value={f.tmp_nome} change={v=>field(key,'tmp_nome',v)}/><Sql label="DELETE dos itens" value={f.tmp_delete} change={v=>field(key,'tmp_delete',v)} insert={t=>append(key,'tmp_delete',t)}/><div className="mix-switches"><CheckBox text="Zerar TMP antes de sincronizar" checked={f.flag1} change={v=>field(key,'flag1',v)}/><CheckBox text="Gravar apenas aprovados" checked={f.flag2} change={v=>field(key,'flag2',v)}/><CheckBox text="Gravar todos classificados" checked={f.flag3} change={v=>field(key,'flag3',v)}/></div><Sql label="INSERT na tabela temporária" value={f.tmp_insert} change={v=>field(key,'tmp_insert',v)} insert={t=>append(key,'tmp_insert',t)}/><Sql label="VALUES do INSERT" value={f.tmp_values} change={v=>field(key,'tmp_values',v)} insert={t=>append(key,'tmp_values',t)}/><Sql label="SELECT / WHERE para gravação" value={f.tmp_selectwhere} change={v=>field(key,'tmp_selectwhere',v)} insert={t=>append(key,'tmp_selectwhere',t)}/></div>})}</div></div></section>
 <section className="divergence-card"><button className="divergence-title" onClick={()=>setDivergenceOpen(!divergenceOpen)}><div><span className="eyebrow dark">COMPARAR DIVERGÊNCIA</span><h2>Campos monitorados</h2><p>Organizados conforme a hierarquia fiscal do Mix Fiscal.</p></div>{divergenceOpen?<ChevronUp/>:<ChevronDown/>}</button>{divergenceOpen&&<><div className="divergence-toolbar"><span>Abra apenas o tributo que deseja conferir.</span><button type="button" onClick={()=>setOpenMasters(openMasters.length===divergenceMasters.length?[]:divergenceMasters.map(master=>master.key))}>{openMasters.length===divergenceMasters.length?<><ChevronUp size={16}/> Recolher tudo</>:<><ChevronDown size={16}/> Expandir tudo</>}</button></div><div className="divergence-masters">{divergenceMasters.map(master=>{const masterOpen=openMasters.includes(master.key);return <article className="divergence-master" key={master.key}><button className="master-title" type="button" onClick={()=>setOpenMasters(current=>masterOpen?current.filter(key=>key!==master.key):[...current,master.key])}><span>{master.title}</span>{masterOpen?<ChevronUp size={19}/>:<ChevronDown size={19}/>}</button>{masterOpen&&<div className="master-grid">{master.sections.flatMap(section=>Object.entries(divergence[section]).map(([group,fields])=><div className="divergence-subcard" key={section+group}><h4>{group}</h4><div className="compact-checks">{fields.map(path=>{const full=`${section}.${path}`;return <CheckBox key={full} text={path.split('.').pop()!.replaceAll('_',' ').toUpperCase()} checked={getDeep(data.comparar_divergencia,full)} change={v=>{const next=structuredClone(data.comparar_divergencia);setDeep(next,full,v);setData({...data,comparar_divergencia:next})}}/>})}</div></div>))}</div>}</article>})}</div></>}</section>
 <button className="primary-button save-bottom" onClick={save}><Check size={18}/> Salvar todas as alterações</button></>}
 </main>
}
function Field({label,value,change}:{label:string,value:string,change:(v:string)=>void}){return <label>{label}<input value={value} onChange={e=>change(e.target.value)}/></label>}
function CheckBox({text,checked,change}:{text:string,checked:boolean,change:(v:boolean)=>void}){return <label className="check"><input type="checkbox" checked={checked} onChange={e=>change(e.target.checked)}/><span>{text}</span></label>}
function Sql({label,value,change,insert}:{label:string,value:string,change:(v:string)=>void,insert:(v:string)=>void}){return <label className="sql-field">{label}<textarea rows={7} spellCheck={false} value={value} onChange={e=>change(e.target.value)}/><span className="sql-tools"><small>Inserir variável:</small>{['{cnpj}','{estado}','{regime_tributario}','{nome_empresa}'].map(x=><button type="button" key={x} onClick={()=>insert(x)}>{x}</button>)}</span></label>}
