"use client";
import { useEffect,useState } from "react";
type Item={id:number;title:string;category:string;content:string;keywords:string;active:boolean};
const empty={title:"",category:"Geral",content:"",keywords:"",active:true};
export default function KnowledgePage(){const [items,setItems]=useState<Item[]>([]),[form,setForm]=useState<Partial<Item>>(empty),[message,setMessage]=useState("");
  async function load(){const r=await fetch("/api/hermes-knowledge-admin",{cache:"no-store"});if(r.status===403){location.href="/login";return;}const d=await r.json();setItems(d.items||[])}
  useEffect(()=>{void load()},[]);
  async function save(){const method=form.id?"PATCH":"POST";const r=await fetch("/api/hermes-knowledge-admin",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();setMessage(r.ok?"Conhecimento salvo e disponível para o assistente.":d.detail);if(r.ok){setForm(empty);await load()}}
  async function remove(id:number){if(!confirm("Excluir este conhecimento?"))return;await fetch(`/api/hermes-knowledge-admin?id=${id}`,{method:"DELETE"});setForm(empty);await load()}
  return <main className="editor-page hermes-page"><header className="editor-header"><div><a className="back" href="/painel/integracoes">← Voltar à API Hermes</a><span className="eyebrow dark">BASE DE CONHECIMENTO</span><h1>O que o assistente deve saber</h1><p>Regras salvas no PostgreSQL e pesquisadas pela API, sem banco vetorial.</p></div></header>{message&&<div className="notice">{message}</div>}
    <section className="profile-card knowledge-editor"><label>Título<input value={form.title||""} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Categoria<input value={form.category||""} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Palavras-chave<input value={form.keywords||""} onChange={e=>setForm({...form,keywords:e.target.value})}/></label><label>Instrução completa<textarea rows={8} value={form.content||""} onChange={e=>setForm({...form,content:e.target.value})}/></label><label className="knowledge-check"><input type="checkbox" checked={form.active!==false} onChange={e=>setForm({...form,active:e.target.checked})}/> Disponível para o assistente</label><div className="hermes-header-actions"><button className="primary-button" onClick={()=>void save()}>{form.id?"Salvar alterações":"Adicionar conhecimento"}</button>{form.id&&<button className="secondary-button" onClick={()=>setForm(empty)}>Cancelar</button>}</div></section>
    <section className="profile-card"><h2>Conteúdo cadastrado</h2>{items.map(item=><div className="team-row" key={item.id}><div><strong>{item.title}</strong><small>{item.category} · {item.keywords||"sem palavras-chave"}</small></div><div className="hermes-header-actions"><span className={`status ${item.active?"concluido":"erro"}`}>{item.active?"Ativo":"Inativo"}</span><button className="secondary-button" onClick={()=>setForm(item)}>Editar</button><button className="secondary-button" onClick={()=>void remove(item.id)}>Excluir</button></div></div>)}</section></main>}
