INSERT INTO templates (nome,criado_em,atualizado_em) VALUES
	 ('VR','2026-08-04 20:38:57','2026-08-04 20:38:57'),
	 ('vazio','2026-08-04 20:38:57','2026-08-04 20:38:57');
INSERT INTO template_secoes (template_id,chave,dados_json) VALUES
	 (1,'pis_cofins','{"view_nome": "mxf_vw_pis_cofins_lucro_real", "view_sql": "SELECT * FROM mxf_vw_pis_cofins_lucro_real\nWHERE STATUS = ''ATIVO''", "tmp_nome": "mxf_tmp_pis_cofins_lucro_real", "tmp_delete": "delete from mxf_tmp_pis_cofins_lucro_real", "flag1": true, "flag2": false, "flag3": false, "tmp_insert": "INSERT INTO mxf_tmp_pis_cofins_lucro_real(\ncodigo_produto, \nean, \nncm, \nncm_ex, \ncod_natureza_receita, \npis_cst_e, \npis_cst_s, \npis_alq_e, \npis_alq_s, \ncofins_cst_e, \ncofins_cst_s, \ncofins_alq_e, \ncofins_alq_s, \nfundamento_legal)", "tmp_values": "%%CODIGO_PRODUTO%%,\n%%EAN%%\t,\n%%NCM%%\t,\n%%NCM_EX%%,\n%%COD_SPED%%,\n%%PIS_CST_E%%\t,\n%%PIS_CST_S%%\t,\n%%PIS_ALQT_E%%\t,\n%%PIS_ALQT_S%%\t,\n%%COFINS_CST_E%%\t,\n%%COFINS_CST_S%%\t,\n%%COFINS_ALQT_E%%\t,\n%%COFINS_ALQT_S%%\t,\n%%FUNDAMENTO_LEGAL%%", "tmp_selectwhere": ""}'),
	 (1,'icms_saida','{"view_nome": "mxf_vw_icms", "view_sql": "SELECT distinct\ncodigo_produto, \nean, \ntipo_mva, \nmva, \nmva_distribuidor, \nre_29560, \ncase when cest = ''00.000.00'' then null else cest end as cest, \nsac_cst, \nsac_alq, \nsac_alqst, \ncase when sac_cst= ''41'' and sac_rbc= ''100.000'' then 0.000 when sac_cst = ''40'' and sac_rbc = ''100.000'' then 0.000 else sac_rbc end as sac_rbc, \nsac_rbcst, \nsas_cst, \nsas_alq, \nsas_alqst, \ncase when sas_cst= ''41'' and sas_rbc= ''100.000'' then 0.000 when sas_rbc = ''40'' and sas_rbc = ''100.000'' then 0.000 else sas_rbc end as sas_rbc, \nsas_rbcst, \nsvc_cst, \nsvc_alq, \nsvc_alqst, \ncase when svc_cst= ''41'' and svc_rbc= ''100.000'' then 0.000 when svc_rbc = ''40'' and svc_rbc = ''100.000'' then 0.000 else svc_rbc end as svc_rbc, \nsvc_rbcst, \nsnc_cst, \nsnc_alq, \nsnc_alqst, \ncase when snc_cst = ''41'' and snc_rbc = ''100.000'' then 0.000 when snc_cst = ''40'' and snc_rbc = ''100.000'' then 0.000 else snc_rbc end as snc_rbc,\nsnc_rbcst,\ncase when fecp is null then 0 else fecp end as fecp,\nstatus\n\n\nFROM mxf_vw_icms\nWHERE STATUS = ''ATIVO''", "tmp_nome": "mxf_tmp_icms_saida_{estado}", "tmp_delete": "delete from mxf_tmp_icms_saida_{estado}", "flag1": true, "flag2": false, "flag3": false, "tmp_insert": "INSERT INTO mxf_tmp_icms_saida_{estado} (\n    codigo_produto,\n    ean,\n    sac_cst,\n    sac_alq,\n    sac_alqst,\n    sac_rbc,\n    sac_rbcst,\n    sas_cst,\n    sas_alq,\n    sas_alqst,\n    sas_rbc,\n    sas_rbcst,\n    svc_cst,\n    svc_alq,\n    svc_alqst,\n    svc_rbc,\n    svc_rbcst,\n    snc_cst,\n    snc_alq,\n    snc_alqst,\n    snc_rbc,\n    cest,\n    FECP,\n    fundamento_legal\n)", "tmp_values": "%%CODIGO_PRODUTO%%,\n    %%EAN%%,\n    %%SAC_CST%%,\n    %%SAC_ALQ%%,\n    %%SAC_ALQ_ST%%,\n    %%SAC_RBC%%,\n    %%SAC_RBC_ST%%,\n    %%SAS_CST%%,\n    %%SAS_ALQ%%,\n    %%SAS_ALQ_ST%%,\n    %%SAS_RBC%%,\n    %%SAS_RBC_ST%%,\n    %%SVC_CST%%,\n    %%SVC_ALQ%%,\n    %%SVC_ALQ_ST%%,\n    %%SVC_RBC%%,\n    %%SVC_RBC_ST%%,\n    %%SNC_CST%%,\n    %%SNC_ALQ%%,\n    %%SNC_ALQ_ST%%,\n    %%SNC_RBC%%,\n    %%CEST%%,\n    %%FECP%%,\n    %%FUNDAMENTO_LEGAL%%", "tmp_selectwhere": ""}'),
	 (1,'icms_entrada','{"view_nome": "mxf_vw_icms_entrada", "view_sql": "SELECT DISTINCT \ncodigo_produto, \nean,  \nei_cst, \nei_alq, \nei_alqst, \nei_rbc, \nei_rbcst, \ned_cst, \ned_alq, \ned_alqst, \ned_rbc, \ned_rbcst, \nes_cst, \nes_alq, \nes_alqst, \nes_rbc, \nes_rbcst, \nnfi_cst, \nnfd_cst, \nnfs_csosn, \nnf_alq, \nstatus\n\nFROM mxf_vw_icms_entrada\nWHERE STATUS = ''ATIVO''", "tmp_nome": "mxf_tmp_icms_entrada_{estado}", "tmp_delete": "delete from mxf_tmp_icms_entrada_{estado}", "flag1": true, "flag2": false, "flag3": false, "tmp_insert": "INSERT INTO mxf_tmp_icms_entrada_{estado}\n(\ncodigo_produto, \nean, \ntipo_mva, \nmva, \nmva_distribuidor, \nmva_data_ini, \nmva_data_fim, \nei_cst, \nei_alq, \nei_alqst, \nei_rbc, \nei_rbcst, \ned_cst, \ned_alq, \ned_alqst, \ned_rbc, \ned_rbcst, \nes_cst, \nes_alq, \nes_alqst, \nes_rbc, \nes_rbcst, \nnfi_cst, \nnfd_cst, \nnfs_csosn, \nnf_alq, \nfundamento_legal)", "tmp_values": "%%CODIGO_PRODUTO%%,\n%%EAN%%,\n%%TIPO_MVA%%,\n%%MVA%%,\n%%MVA_DISTRIBUIDOR%%,\n%%MVA_DATA_INI%%,\n%%MVA_DATA_FIM%%,\n%%EI_CST%%,\n%%EI_ALQ%%,\n%%EI_ALQST%%,\n%%EI_RBC%%,\n%%EI_RBCST%%,\n%%ED_CST%%,\n%%ED_ALQ%%,\n%%ED_ALQST%%,\n%%ED_RBC%%,\n%%ED_RBCST%%,\n%%ES_CST%%,\n%%ES_ALQ%%,\n%%ES_ALQST%%,\n%%ES_RBC%%,\n%%ES_RBCST%%,\n%%NFI_CST%%,\n%%NFD_CST%%,\n%%NFS_CSOSN%%,\n%%NF_ALQ%%,\n%%FUNDAMENTO_LEGAL%%", "tmp_selectwhere": ""}'),
	 (1,'ibs_cbs','{"view_nome": "MXF_VW_CBS_IBS", "view_sql": "SELECT * FROM MXF_VW_CBS_IBS WHERE EMPRESA=''{cnpj}''", "tmp_nome": "MXF_TMP_CBS_IBS", "tmp_delete": "delete from MXF_TMP_CBS_IBS", "flag1": true, "flag2": false, "flag3": true, "tmp_insert": "INSERT INTO MXF_TMP_CBS_IBS\n(CODIGO_PRODUTO, \nEAN, \nCCLASSTRIB, \nCST_CBS_IBS, \nALQ_CBS, \nRBC_CBS, \nALQ_IBS, \nALQ_IBS_MUN, \nRBC_IBS, \nRBC_IBS_MUN, \nALQ_IS, \nALQ_IS_ESPEC, \nCST_IS, \nCCLASSTRIB_IS, \nFUNDAMENTO_LEGAL,\nempresa\n)", "tmp_values": "%%CODIGO_PRODUTO%%, \n%%EAN%%, \n%%cclass_trib%%, \n%%ibs_cbs_cst%%, \n%%cbs_alq%%, \n%%cbs_alq_rbc%%, \n%%ibs_uf_alq%%, \n%%ibs_mun_alq%%, \n%%ibs_uf_alq_rbc%%, \n%%ibs_mun_alq_rbc%%, \n%%is_alq%%, \n%%is_alq_espec%%, \nnull, \n%%is_cclass_trib%%, \n%%cbs_fundamento_legal%%,\n''{cnpj}''", "tmp_selectwhere": ""}'),
	 (2,'pis_cofins','{"view_nome": "", "view_sql": "", "tmp_nome": "", "tmp_delete": "", "flag1": true, "flag2": false, "flag3": false, "tmp_insert": "", "tmp_values": "", "tmp_selectwhere": ""}'),
	 (2,'icms_saida','{"view_nome": "", "view_sql": "", "tmp_nome": "", "tmp_delete": "", "flag1": true, "flag2": false, "flag3": false, "tmp_insert": "", "tmp_values": "", "tmp_selectwhere": ""}'),
	 (2,'icms_entrada','{"view_nome": "", "view_sql": "", "tmp_nome": "", "tmp_delete": "", "flag1": true, "flag2": false, "flag3": false, "tmp_insert": "", "tmp_values": "", "tmp_selectwhere": ""}'),
	 (2,'ibs_cbs','{"view_nome": "", "view_sql": "", "tmp_nome": "", "tmp_delete": "", "flag1": true, "flag2": false, "flag3": false, "tmp_insert": "", "tmp_values": "", "tmp_selectwhere": ""}');

