"use client";
import { FormEvent,useEffect,useState } from "react";
import { ArrowLeft,KeyRound,Save,UserRound } from "lucide-react";

export default function ProfilePage(){
 const [user,setUser]=useState({nome:'',email:''}),[message,setMessage]=useState('');
 useEffect(()=>{fetch('/api/profile').then(r=>r.json()).then(setUser)},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);if(form.get('nova_senha')!==form.get('confirmar_senha'))return setMessage('A confirmação da nova senha não confere.');const r=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({login:form.get('login'),senha_atual:form.get('senha_atual'),nova_senha:form.get('nova_senha')})});const j=await r.json();if(!r.ok)return setMessage(j.detail);setUser(j);setMessage('Usuário e segurança atualizados com sucesso.');e.currentTarget.reset();}
 return <main className="editor-page narrow"><header className="editor-header"><div><a className="back" href="/painel"><ArrowLeft size={17}/> Voltar ao painel</a><span className="eyebrow dark">MINHA CONTA</span><h1>Login e senha</h1><p>Uma tela simples para alterar os dados usados na entrada.</p></div></header>{message&&<div className="notice"><span>{message}</span><button onClick={()=>setMessage('')}>×</button></div>}<form className="profile-card" onSubmit={save}><div className="profile-avatar"><UserRound/></div><label>Usuário de acesso<input name="login" value={user.email} onChange={e=>setUser({...user,email:e.target.value})} minLength={3} required/><small>Este é o nome digitado na tela de login.</small></label><hr/><div className="section-label"><KeyRound size={18}/><strong>Confirmar alteração</strong><small>Digite a senha atual. A nova senha é opcional.</small></div><label>Senha atual<input name="senha_atual" type="password" autoComplete="current-password" required/></label><label>Nova senha (opcional)<input name="nova_senha" type="password" autoComplete="new-password" minLength={12}/></label><label>Repita a nova senha<input name="confirmar_senha" type="password" autoComplete="new-password" minLength={12}/></label><p className="password-rule">Se alterar: mínimo de 12 caracteres com letra, número e símbolo.</p><button className="primary-button"><Save size={18}/> Salvar login e senha</button></form></main>
}
