"use client";
import { FormEvent,useEffect,useState } from "react";
import { ArrowLeft,KeyRound,Save,UserRound } from "lucide-react";

export default function ProfilePage(){
 const [user,setUser]=useState({nome:'',email:''}),[message,setMessage]=useState('');
 useEffect(()=>{fetch('/api/profile').then(r=>r.json()).then(setUser)},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);if(form.get('nova_senha')!==form.get('confirmar_senha'))return setMessage('A confirmação da nova senha não confere.');const r=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({nome:form.get('nome'),senha_atual:form.get('senha_atual'),nova_senha:form.get('nova_senha')})});const j=await r.json();if(!r.ok)return setMessage(j.detail);setUser(j);setMessage('Perfil atualizado. Use a nova senha no próximo acesso.');e.currentTarget.reset();}
 return <main className="editor-page narrow"><header className="editor-header"><div><a className="back" href="/painel"><ArrowLeft size={17}/> Voltar ao painel</a><span className="eyebrow dark">MINHA CONTA</span><h1>Perfil e segurança</h1><p>Atualize seu nome e proteja o acesso ao painel.</p></div></header>{message&&<div className="notice"><span>{message}</span><button onClick={()=>setMessage('')}>×</button></div>}<form className="profile-card" onSubmit={save}><div className="profile-avatar"><UserRound/></div><label>Nome de exibição<input name="nome" value={user.nome} onChange={e=>setUser({...user,nome:e.target.value})} minLength={2} required/></label><label>E-mail<input value={user.email} disabled/></label><hr/><div className="section-label"><KeyRound size={18}/><strong>Alterar senha</strong><small>Deixe a nova senha vazia para alterar somente o nome.</small></div><label>Senha atual<input name="senha_atual" type="password" autoComplete="current-password" required/></label><label>Nova senha<input name="nova_senha" type="password" autoComplete="new-password" minLength={12}/></label><label>Confirmar nova senha<input name="confirmar_senha" type="password" autoComplete="new-password" minLength={12}/></label><p className="password-rule">Use no mínimo 12 caracteres, incluindo letra, número e símbolo.</p><button className="primary-button"><Save size={18}/> Salvar perfil</button></form></main>
}
